version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
formats:
  - pdf
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
